kind: Deployment
apiVersion: apps/v1
metadata:
  name: payment-deployment
  namespace: auction-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      name: payment
      labels:
        app: payment
    spec:
      containers:
        - 
          name: payment
          image: vishu0210/payment:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: payment-configmap
            - secretRef: 
                name: payment-secrets
          resources:
            requests: 
              cpus: '1'
              memory: 256mi
            limits:
              cpus: '1.5'
              memory: 526mi