services:

  auctionx:
    image: ${USERNAME}/auctionx:${GIT_SHA}
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile.auctionx
      target: production
      attestations:
        - type=sbom
        - type=provenance,mode=max

  payment:
    image: ${USERNAME}/payment:${GIT_SHA}
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile.payment
      target: production
      attestations:
        - type=sbom
        - type=provenance,mode=max

  notification:
    image: ${USERNAME}/notification:${GIT_SHA}
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile.notification
      target: production
      attestations:
        - type=sbom
        - type=provenance,mode=max