services:

  auctionx:
    image: ${USERNAME}/auctionx:${GIT_SHA}
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile.auctionx
      target: production

  payment:
    image: ${USERNAME}/payment:${GIT_SHA}
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile.payment
      target: production

  notification:
    image: ${USERNAME}/notification:${GIT_SHA}
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile.notification
      target: production


  frontend:
    image: ${USERNAME}/frontend:${GIT_SHA}
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile.frontend
      target: production
