services:

  auctionx:
    image: ${USERNAME}/auctionx:${GIT_SHA}
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile.auctionx
      target: production

  payment:
    image: ${USERNAME}/payment:${GIT_SHA}
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile.payment
      target: production

  notification:
    image: ${USERNAME}/notification:${GIT_SHA}
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile.notification
      target: production
  
  auctionx:
    image: ${USERNAME}/auctionx:${GIT_SHA}
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile.auctionx
      target: production
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_API_WS_URL: ${NEXT_PUBLIC_API_WS_URL}