kind: ConfigMap
apiVersion: v1
metadata:
  name: notification-configs
  namespace: auction-backend 
data:
  # <service-name>.<namespace>.svc.cluster.local:<port>
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka.auction-data.svc.cluster.local:9092"
  SPRING_MAIL_HOST: "mailpit.auction-backend.svc.cluster.local"
  SPRING_MAIL_PORT: "1025"